config/routes.rb
Rails.application.routes.draw do
  get 'pages/secret'
  resources :email_pages
  resources :admin_pages
  resources :welcoms
  resources :user_roles
  resources :teachers
  # get 'controllerName/method or action'
  get 'change' => 'teachers#change'
  resources :students
  # get 'changeS' => 'students#change'
  resources :roles
  resources :profiles
  resources :permissions
  resources :courses
  resources :cohorts
  resources :administrators
  # resources :admins
  # root to: 'admins#new'
  get 'admins/new' => 'admins#new', as: :new_admin
  post 'admins' => 'admins#create'
  get '/login' => 'sessions#new'
  post '/login'=>  'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/welcoms' => 'welcoms#index' 
  root 'welcoms#index'
  # root to: 'admins#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true
end

app/models/administrator.rb
class Administrator < ApplicationRecord
   has_one :role
   
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_one :teacher
  # belongs_to :course
  has_one :course
  has_many :students
  has_many :cohort_students
  has_many :students, through: :cohort_students
  validates_presence_of :cohort_name, :cohort_start_date, :cohort_end_date
end

app/models/cohort_student.rb
class CohortStudent < ApplicationRecord
  belongs_to :cohort
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
    # belongs_to :teacher
    # belongs_to :student
    # has_one :cohort
    belongs_to :cohort, optional: true
    validates_presence_of :course_name
    validates :course_hours, numericality: { only_integer: true, greater_than: 0, message: "A course has to have at leat 1 hour, nothing less. Sucka!"}
    # validates_numericality_of :course_hours, :message=>"Error Message - Enter hours"
end

app/models/education.rb
class Education < ApplicationRecord
   
end

app/models/permission.rb
class Permission < ApplicationRecord
   belongs_to :roles
end

app/models/profile.rb
class Profile < ApplicationRecord
    # has_one :teacher
    # has_one :student
    # has_one :administrator
end

app/models/role.rb
class Role < ApplicationRecord
   has_many :permissions
   belongs_to :user_role
   
end

app/models/student.rb
class Student < ApplicationRecord
    # has_one :role
    # has_one :education
    has_one :profile
    # has_one :education
    # has_one :cohort
    has_many :cohorts
    has_many :cohort_students
    has_many :cohorts, through: :cohort_students
    validates_presence_of :username, :password, :first_name, :last_name, :age, :education
    validates :age, numericality: { only_integer: true, greater_than: 0, less_than: 150}
    # , message: "Error Message - Enter your age"
    # validates_numericality_of :age, 
end 

app/models/teacher.rb
class Teacher < ApplicationRecord
    # has_one :role
    # has_one :education
    # has_one :cohort
    # has_one :education_level
    # has_one :profile
    belongs_to :cohort, optional: true

    validates_presence_of :username, :password, :first_name, :last_name, :age, :salary, :education
    validates :age, numericality: { only_integer: true, greater_than: 0, less_than: 150, message: "Listen sucka, you ain't older than 150 years old. So make it right!"}
    validates :salary, numericality: { greater_than: 0, message: "Please enter an amount greater than %{value} dollars, Sucka!"}
    
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  has_one :teacher
  has_one :student
  has_one :administrator
  has_many :roles
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index
        @students = Student.all
      end
    
      def show
        @student = Student.find(params[:id])
      end

      def new
        @student = Student.new
        # @edu= Education.all.map{ |e| [ e.education, e.id]}
        # @edu = Education.all
      end

      def create
        @student = Student.new(student_params)
        puts @student.inspect
        if @student.save
          redirect_to students_path
        else
          # puts @student.errors.messages.join(',')
          render "new"
        end
      end
       
      def edit
        @student = Student.find(params[:id])
      end
    
      def update
        @student = Student.find(params[:id])
     
        if @student.update(student_params)
          redirect_to @student
        else
          render 'new'
        end
      end
    
      def destroy
        @student = Student.find(params[:id])
        @student.destroy
        respond_to do |format|
          format.html {render redirect_to students_path}
          format.js { render '/courses/index.js.erb'}
        end
        # redirect_to students_path
      end
    
      private
        def student_params
          params.require(:student).permit(:username , :password, :first_name, :last_name,
          :age, :education)
        end
    
    end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/cohort_helper.rb
module CohortHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/role_helper.rb
module RoleHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/welcom_helper.rb
module WelcomHelper
end

app/views/students/edit.html.erb
<h1 class="text-center">Edit a Student</h1>
<hr>


<%= form_with scope: :student, model: @student, local: true do |form| %>
  <div class="form-group">
    <%= form.label :username %><br>
    <%= form.text_field :username %>
  </div>
 
  <div class="form-group">
    <%= form.label :password %><br>
     <%= form.text_field :password%>
  </div>
 
 <div class="form-group">
    <%= form.label :first_name %><br>
     <%= form.text_field :first_name %>
  </div>
  <div class="form-group">
    <%= form.label :last_name %><br>
     <%= form.text_field :last_name %>
  </div>
  <div class="form-group">
    <%= form.label :age %><br>
    <%= @student.errors.full_messages_for(:age) if @student.errors.include?(:age) %>
     <%= form.text_field :age %>
  </div>
  <div class="form-group">
    <%= form.label :education %>
     <%= form.text_field :education %>
  </div>
  <br>
  <div>
     <button><%= form.submit %><button>
  </div>
<% end %>

<%= link_to 'Dashboard', admin_pages_path(@students) %>

app/views/students/index.html.erb
<h1 class="d-flex justify-content-center">Student Dashboard</h1>


<h3 class="d-flex justify-content-center">Administrator</h1>

<hr>


<div class="container">
  <div class="row">
   <ul class="nav nav-tabs">
  <li class="nav-item">
    <p class="nav-link "> <%= link_to "Create", new_student_path %></p>
  </li>
</ul>
</div>
</div>
<h1>List of Students</h1>
<% if @students.blank? %>
  <p> There are no students currently in the system.</p>
<% else %>
<div class="container">
<div class="row"> 
<% @students.each do |student|%>
    <div class="col-4">
        <div class="card border border-primary rounded" style="width: 18rem;">
        <table>
          <tr id="student<%= student.id %>" class="list-group">
            <td class="list-group-item">Student-ID: <%= student.id%> </td><br>
            <td class="list-group-item">Student-Username: <%= student.username%> </td>
            <td class="list-group-item">First Name: <%= student.first_name%> </td>
            <td class="list-group-item">Last Name: <%= student.last_name%> </td>
            <td class="list-group-item">Age: <%= student.age%> </td>
            <td class="list-group-item">Education: <%= student.education%> </td>
            <%# <td class="list-group-item">Cohort-ID: <%= student.cohort_id%> 
            
            <td><%= link_to 'Edit', edit_student_path(student.id) %></td>
            <td><%= link_to 'Destroy', student_path(student.id), remote: true,
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td><br>
          </tr>
        </table>
        </div>
      </div>
      <% end %>
    </div>
    
  </div>
<% end %>

app/views/students/index.js.erb
let studentTD<%= @students.id %> = document.querySelector("#student" + <%= @students.id %>)
 studentTD<%= @students.id %>.remove();

 

app/views/students/new.html.erb
<h1 class="text-center">Create a Student</h1>
<hr>




<%= form_with scope: :student, model: @student, local: true do |form| %>
  <div class="form-group">
    <%= form.label :username %><br>
    <%= form.text_field :username %>
  </div>
 
  <div class="form-group">
    <%= form.label :password %><br>
     <%= form.text_field :password%>
  </div>
 
 <div class="form-group">
    <%= form.label :first_name %><br>
     <%= form.text_field :first_name %>
  </div>
  <div class="form-group">
    <%= form.label :last_name %><br>
     <%= form.text_field :last_name %>
  </div>
  <div class="form-group">
    <%= form.label :age %><br>
    <%= @student.errors.full_messages_for(:age) if @student.errors.include?(:age) %>
     <%= form.text_field :age %>
     
  </div>
  <div>
    <p class="form-control input-sm selectpicker"><%= form.label :education_id %>
      <%= form.label :education %>
     <%# <%= form.text_field :education%>
     <%= form.select(:education, options_for_select([['High School'], ['College'], ['Masters'], ['PHD']]), { include_blank: true }) %>
    
    
  
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/show.html.erb
<h1 class="text-center">View a Student</h1>
<hr>
 <div class="container">
  <div class="row"> 
      <div class="col-4"> 
      <div class="card border border-primary rounded" style="width: 18rem;"> 
       <table>  
            <tr>
                <td class="list-group-item">Student-ID: <%= @student.id%> </td>
                <td class="list-group-item">Student Username: <%= @student.username%> </td>
                <td class="list-group-item">First Name: <%= @student.first_name%> </td>
                <td class="list-group-item">Last Name: <%= @student.last_name%> </td>
                <td class="list-group-item">Age: <%= @student.age%> </td>
                <td class="list-group-item">Education Level: <%= @student.education%> </td>
            </tr>
        </table>
      </div>
      </div>
   </div>
</div>      
<br>
<%= link_to 'Dashboard', admin_pages_path(@students) %>