config/routes.rb
Rails.application.routes.draw do
  get 'pages/secret'
  resources :email_pages
  resources :admin_pages
  resources :welcoms
  resources :user_roles
  resources :teachers
  # get 'controllerName/method or action'
  get 'change' => 'teachers#change'
  resources :students
  # get 'changeS' => 'students#change'
  resources :roles
  resources :profiles
  resources :permissions
  resources :courses
  resources :cohorts
  resources :administrators
  # resources :admins
  # root to: 'admins#new'
  get 'admins/new' => 'admins#new', as: :new_admin
  post 'admins' => 'admins#create'
  get '/login' => 'sessions#new'
  post '/login'=>  'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/welcoms' => 'welcoms#index' 
  root 'welcoms#index'
  # root to: 'admins#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true
end

app/models/administrator.rb
class Administrator < ApplicationRecord
   has_one :role
   
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_one :teacher
  # belongs_to :course
  has_one :course
  has_many :students
  has_many :cohort_students
  has_many :students, through: :cohort_students
  validates_presence_of :cohort_name, :cohort_start_date, :cohort_end_date
end

app/models/cohort_student.rb
class CohortStudent < ApplicationRecord
  belongs_to :cohort
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
    # belongs_to :teacher
    # belongs_to :student
    # has_one :cohort
    belongs_to :cohort, optional: true
    validates_presence_of :course_name
    validates :course_hours, numericality: { only_integer: true, greater_than: 0, message: "A course has to have at leat 1 hour, nothing less. Sucka!"}
    # validates_numericality_of :course_hours, :message=>"Error Message - Enter hours"
end

app/models/education.rb
class Education < ApplicationRecord
   
end

app/models/permission.rb
class Permission < ApplicationRecord
   belongs_to :roles
end

app/models/profile.rb
class Profile < ApplicationRecord
    # has_one :teacher
    # has_one :student
    # has_one :administrator
end

app/models/role.rb
class Role < ApplicationRecord
   has_many :permissions
   belongs_to :user_role
   
end

app/models/student.rb
class Student < ApplicationRecord
    # has_one :role
    # has_one :education
    has_one :profile
    # has_one :education
    # has_one :cohort
    has_many :cohorts
    has_many :cohort_students
    has_many :cohorts, through: :cohort_students
    validates_presence_of :username, :password, :first_name, :last_name, :age, :education
    validates :age, numericality: { only_integer: true, greater_than: 0, less_than: 150}
    # , message: "Error Message - Enter your age"
    # validates_numericality_of :age, 
end 

app/models/teacher.rb
class Teacher < ApplicationRecord
    # has_one :role
    # has_one :education
    # has_one :cohort
    # has_one :education_level
    # has_one :profile
    belongs_to :cohort, optional: true

    validates_presence_of :username, :password, :first_name, :last_name, :age, :salary, :education
    validates :age, numericality: { only_integer: true, greater_than: 0, less_than: 150, message: "Listen sucka, you ain't older than 150 years old. So make it right!"}
    validates :salary, numericality: { greater_than: 0, message: "Please enter an amount greater than %{value} dollars, Sucka!"}
    
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  has_one :teacher
  has_one :student
  has_one :administrator
  has_many :roles
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end

  def change
    @teachers = Teacher.all
  end

  def show
       @teacher  = Teacher.find(params[:id])
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher= Teacher.new(teacher_params)
    puts @teacher.inspect
    if @teacher.save
      redirect_to teachers_path
    else
      # puts @teacher.errors.messages.join(',')
      render "new"
  end
end

  
  def edit
    @teacher = Teacher.find(params[:id])
  end

  def update
    @teacher = Teacher.find(params[:id])
    #@teacher_params.inspect
    if @teacher.update(teacher_params)
      redirect_to @teacher
    else
       render 'new' 
    end
  end

  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
 
    redirect_to teachers_path
  end

  private
    def teacher_params
      params.require(:teacher).permit(:username , :password, :first_name, :last_name,
      :age, :salary, :education)
    end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/cohort_helper.rb
module CohortHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/role_helper.rb
module RoleHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/welcom_helper.rb
module WelcomHelper
end

app/views/teachers/change.html.erb
<h1 class="text-center">List of Teachers</h1>
<hr>
<% if @teachers.blank? %>
<p> There are no teachers currently in the system.</p>
<% else %>
<div class="container">
<div class="row"> 
<% @teachers.each do |teacher|%>
    <div class="col-4"> 
    <div class="card border border-primary rounded" style="width: 18rem;">
    <table>
        <tr id="teacher<%= teacher.id %>" class="list-group">
        <td class="list-group-item">Teacher-ID: <%= teacher.id%> </td>
        <td class="list-group-item">Teacher-Username: <%= teacher.username%> </td>
        <td class="list-group-item">First Name: <%= teacher.first_name%> </td>
        <td class="list-group-item">Last Name: <%= teacher.last_name%> </td>
        <td class="list-group-item">Age: <%= teacher.age%> </td>
        <td class="list-group-item">Salary: $<%= teacher.salary%> </td>
        <td class="list-group-item">Education: <%= teacher.education%> </td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher.id) %></td>
        <td><%= link_to 'Destroy', teacher_path(teacher.id), remote: true,
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td><br>
        </tr>
        </table>
        </div>
      </div>
      <% end %>
    </div>
    
  </div>
<% end %>
<%= link_to 'Dashboard', admin_pages_path(@teachers) %>

app/views/teachers/change.js.erb
let teacherTD<%= @teachers.id %> = document.querySelector("#teacher" + <%= @teachers.id %>)
 teacherTD<%= @teachers.id %>.remove();

<%# <tr id="teacher<%= teacher.id %>

app/views/teachers/edit.html.erb
<h1 class="text-center">Teacher#edit</h1>
<hr>


<%= form_with scope: :teacher, model: @teacher, local: true do |form| %>
  <div class="form-group">
    <%= form.label :username %><br>
    <%= form.text_field :username %>
  </div>
 
  <div class="form-group">
    <%= form.label :password %><br>
     <%= form.text_field :password%>
  </div>
 
 <div class="form-group">
    <%= form.label :first_name %><br>
     <%= form.text_field :first_name %>
  </div>
  <div class="form-group">
    <%= form.label :last_name %><br>
     <%= form.text_field :last_name %>
  </div>
  <div class="form-group">
    <%= form.label :age %><br>
     <%= form.text_field :age %>
  </div>
  <div class="form-group">
     <%= form.label :age %><br>
     <%= @teacher.errors.full_messages_for(:age) if @teacher.errors.include?(:age) %>
     <%= form.text_field :age %>
  </div>
  <div class="form-group">
     <%= form.label :salary %><br>
     <%= @teacher.errors.full_messages_for(:salary) if @teacher.errors.include?(:salary) %>
     <%= form.text_field :salary%>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Dashboard', admin_pages_path(@teachers) %>

app/views/teachers/index.html.erb
<h1 class="d-flex justify-content-center">Teacher Dashboard</h1>


<h3 class="d-flex justify-content-center">Administrator</h1>

<hr>


<div class="container">
  <div class="row">
   <ul class="nav nav-tabs">
  <li class="nav-item">
     <p class="nav-link" > <%= link_to "Create", new_teacher_path %></p>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="change">Update</a>
  </li>
</ul>
</div>
</div>

app/views/teachers/new.html.erb
<h1 class="text-center">Create a Teacher</h1>
<hr>



<%= form_with scope: :teacher, model: @teacher, local: true do |form| %>
  <div class="form-group">
    <%= form.label :username %><br>
    <%= form.text_field :username %>
  </div>
 
  <div class="form-group">
    <%= form.label :password %><br>
     <%= form.text_field :password%>
  </div>
 
 <div class="form-group">
    <%= form.label :first_name %><br>
     <%= form.text_field :first_name %>
  </div>
  <div class="form-group">
    <%= form.label :last_name %><br>
     <%= form.text_field :last_name %>
  </div>
  <div>
 
    <%= form.label :age %><br>
     <%= @teacher.errors.full_messages_for(:age) if @teacher.errors.include?(:age) %>
     <%= form.text_field :age %>
  </div>
  <div>
  
    <%= form.label :salary %><br>
    <%= @teacher.errors.full_messages_for(:salary) if @teacher.errors.include?(:salary) %>
     <%= form.text_field :salary%>
  </div>
  <div>
    <%= form.label :education %><br>
    <%= form.select(:education, options_for_select([['High School'], ['College'], ['Masters'], ['PHD']]), { include_blank: true }) %>
     <%# <%= form.text_field :education %> 
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/show.html.erb
<h1 class="text-center">View a Teacher</h1>
<hr>
<div class="container">
  <div class="row"> 
    <div class="col-4"> 
     <div class="card border border-primary rounded" style="width: 18rem;"> 
        <table> 
            <tr class="list-group">
                <td class="list-group-item">Teacher-ID: <%= @teacher.id%> </td>
                <td class="list-group-item">Teacher-Username: <%= @teacher.username%> </td>
                <td class="list-group-item">First Name: <%= @teacher.first_name%> </td>
                <td class="list-group-item">Last Name: <%= @teacher.last_name%> </td>
                <td class="list-group-item">Age: <%= @teacher.age%> </td>
                <td class="list-group-item">Salary $<%= @teacher.salary%> </td>
                <td class="list-group-item">Education Level: <%= @teacher.education%> </td>
            </tr>
        </table>
    </div>
</div>
</div>


<br>

<%= link_to 'Dashboard', admin_pages_path(@teachers) %>